name: Build Android APK (Blank App)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: |
          npm install
          npm run build
          npm install @capacitor/cli --save-dev
          npx cap add android || echo "Android folder already exists"
          npx cap copy
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
          cd android
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: BlankApp-Debug-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
